### ISSUE TITLE
[LauncherStartScreen] NoClassDefFound

### ISSUE THREAD

**Issue by iBuseWinner** [GravitLauncher/LauncherModules#12]
При самом первом запуске лаунчера выбивает следующую ошибку:
`Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: pro/gravit/launcher/client/events/ClientGuiPhase
        at pro.gravit.launchermodules.startscreen.ModuleImpl.init(ModuleImpl.java:29)
        at pro.gravit.launcher.modules.impl.SimpleModuleManager.initModules(SimpleModuleManager.java:77)
        at pro.gravit.launchserver.LaunchServerStarter.main(LaunchServerStarter.java:62)
Caused by: java.lang.NoClassDefFoundError: pro/gravit/launcher/client/events/ClientGuiPhase
        ... 3 more
Caused by: java.lang.ClassNotFoundException: pro.gravit.launcher.client.events.ClientGuiPhase
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more`

**Comment by xDev789** [comment]
Вас не смущает то, что Вы засунули клиентский модуль в папку с лаунчсерверными?
