### ISSUE TITLE
PaperPatch

### ISSUE THREAD

**Issue by daniorio** [GravitLauncher/LauncherModules#7]
Классы asm'a внутри модуля

**Comment by daniorio** [comment]
Да и сам модуль не рабочий нихрена

**Comment by Zaxar163** [comment]
Вот ты нихера не рабочий. Скажу 1 - асм в половине ядер есть и добавлять его туда опасно из-за конфликта версий.

**Comment by Zaxar163** [comment]
Мало того, без дебага и ошибки помочь не смогу.

**Comment by daniorio** [comment]
> 
> 
> Вот ты не рабочий. Скажу 1 - асм в половине ядер есть и добавлять его туда опасно из-за конфликта версий.

Вот это херня ответ. Модуль сделан только для спигота, насколько я понимаю, а там, как раз-таки нет asm'a.

**Comment by daniorio** [comment]
> 
> 
> Мало того, без дебага и ошибки помочь не смогу.

java.lang.VerifyError: Cannot inherit from final class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.bukkit.craftbukkit.Main.main(Main.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.papermc.paperclip.Paperclip.main(Paperclip.java:54)
        at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:183)
        at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:209)

**Comment by Zaxar163** [comment]
Патчи закреплены в оффтопе дискорда.
